name: CI-CD test

on:
  pull_request:
    branches:
      - master
      - main
      - develop

  push:
    branches:
      - master
      - main
      - develop
jobs:
  limpa-release:
    name: limpa as releases anteriores
    runs-on: [self-hosted, linux]
    steps:
      - name: diretorio
        run: rm -Rf "${{ github.workspace }}"

  data-atual:
    needs: limpa-release
    name: pega a data do deploy
    runs-on: [self-hosted, linux]
    steps:
      - name: Get date
        run: |
          echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

  clone:
    needs: data-atual  
    name: clonando o repositório atual para a realização do deploy
    runs-on: [self-hosted, linux]    
    steps:
      - name: Checkout
        uses: actions/checkout@v3    

  deploy:
    needs: clone
    name: efetuando o processo de deploy no servidor remoto
    runs-on: [self-hosted, linux]
    steps:
      - name: Create release teste
        shell: bash
        run: bash -x /home/deploy/deploy.sh ${GITHUB_REF#refs/heads/}
  
  muda-versao:
    needs: deploy
    name: muda a versao do sistema no servidor
    runs-on: [self-hosted, linux]
    steps:
      - name: Cria a release do deploy
        shell: bash
        run: bash -x /home/deploy/deploy.sh ${GITHUB_REF#refs/heads/} ${{ github.workspace }} ${{ github.event.repository.name }}

  reiniciando-servicos:
    needs: muda-versao
    name: reinicia os serviços do servidor
    runs-on: [self-hosted, linux]
    steps:
      - name: Reincia servicos
        shell: bash
        run: systemctl status cron
