name: CI-CD test

on:
  pull_request:
    branches:
      - master
      - main
      - develop

  push:
    branches:
      - master
      - main
      - develop
jobs:
  deploy:
    name: deploy no server remoto
    runs-on: [self-hosted, linux]
    steps:

      - name: Get date
        run: |
          echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Echo env date
        run: |
          echo "${{ env.current_date }}"

      - name: pegar a branch
        run: |
          echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}"
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Create release
        shell: bash
        run: bash -x /home/deploy/deploy.sh $BRANCH_NAME

      - name: Create release teste
        shell: bash
        run: bash -x /home/deploy/deploy.sh ${GITHUB_REF#refs/heads/}
