name: CI-CD test

on:
  pull_request:
    branches:
      - master
      - main
      - develop

  push:
    branches:
      - master
      - main
      - develop

jobs:
  deploy:
    name: deploy no server remoto
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ssh-key: ' ${{ secrets.SSH_KEY }}'       

      - name: Get current date
        run: |
          echo "::set-output name=VERSION::$(date '+%Y%m%d%H%M')"

      - name: Change Release - ls current
        shell: bash
        run: |
          echo "current"
          ls -lah /wwwroot/ci-cd/current

      - name: Change Release - ls ci-cd
        shell: bash
        run: |          
          echo "ci-cd"
          echo "$VERSION"
          ls -lah /wwwroot/ci-cd/
          echo "remove"
                  
      - name: Create release
        shell: bash
        run: |
            mkdir -p /wwwroot/ci-cd/releases/
            mv /wwwroot/ci-cd/ci-cd/ /wwwroot/ci-cd/releases/$VERSION
      
      - name: Change Release - Remove current
        shell: bash
        run: |          
          rm /wwwroot/ci-cd/current

      - name: Change Release - create symbolic link
        shell: bash
        run: |
            ln -s /wwwroot/ci-cd/releases/$VERSION /wwwroot/ci-cd/current
            ls -lah /wwwroot/ci-cd/

