name: CI-CD test

on:
  pull_request:
    branches:
      - master
      - main
      - develop

  push:
    branches:
      - master
      - main
      - develop
jobs:
  diretorio-de-trabalho:
    name: confere o diretório de trabalho
    runs-on: [self-hosted, linux]
    steps:
      - name: diretorio
        shell: bash
        run: |
              echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV
              echo "WORK_DIR=$(pwd)" >> ${{ env.WORK_DIR }}
              echo "o workdir é => ${{ env.WORK_DIR }} "
              echo "o workdir é => $GITHUB_ENV"              
  limpa-release:
    needs: diretorio-de-trabalho
    name: limpa as releases anteriores
    runs-on: [self-hosted, linux]
    steps:
      - name: diretorio
        run: echo "rm -Rf echo ${{ env.WORK_DIR }}"
  data-atual:
    needs: limpa-release
    name: pega a data do deploy
    runs-on: [self-hosted, linux]
    steps:
      - name: Get date
        run: |
          echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
  clone:
    needs: data-atual  
    name: clone do reposiorio
    runs-on: [self-hosted, linux]    
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
        
  deploy:
    needs: clone
    name: deploy no server remoto
    runs-on: [self-hosted, linux]
    steps:
        
      - name: Create release teste
        shell: bash
        run: bash -x /home/deploy/deploy.sh ${GITHUB_REF#refs/heads/}
  
  muda-versao:
    needs: deploy
    name: muda a versao do sistema no servidor
    runs-on: [self-hosted, linux]
    steps:
        
      - name: Create release teste
        shell: bash
        run: bash -x /home/deploy/deploy.sh ${GITHUB_REF#refs/heads/}

  reiniciando-servicos:
    needs: muda-versao
    name: reinicia os serviços do servidor
    runs-on: [self-hosted, linux]
    steps:
        
      - name: Reincia servicos
        shell: bash
        run: systemctl status cron
