name: CI-CD test

on:
  pull_request:
    branches:
      - master
      - main
      - develop

  push:
    branches:
      - master
      - main
      - develop
jobs:
  deploy:
    name: deploy no server remoto
    runs-on: [self-hosted, linux]
    steps:

      - name: Get date
        run: |
          echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Echo env date
        run: |
          echo "${{ env.current_date }}"

      - name: pegar a branch
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"

      - name: Branch name
        run: echo running on branch $${{ github.head_ref }}
            echo "Slug variables"
            echo " - ${{ env.GITHUB_BASE_REF_SLUG }}"
            echo " - ${{ env.GITHUB_REPOSITORY_SLUG }}"
            echo "Slug URL variables"
            echo " - ${{ env.GITHUB_REF_SLUG_URL }}"
            echo " - ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
            echo " - ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
            echo " - ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
            echo "process.env.GITHUB_HEAD_REF" 
            echo "process.env.GITHUB_REF"
            echo "process.env.GITHUB_REF.split('/')[2]"
            echo "process.env.GITHUB_EVENT_NAME"

      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"

      - name: Create release
        shell: bash
        run: bash -x /home/deploy/deploy.sh
