name: CI-CD test

on:
  pull_request:
    branches:
      - master
      - main
      - develop

  push:
    branches:
      - master
      - main
      - develop
jobs:
  deploy:
    name: deploy no server remoto
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ssh-key: ' ${{ secrets.SSH_KEY }}'       

      - name: Branch name
        run: echo running on branch $${{ github.head_ref }}

      - name: Get current date
        run: echo "::set-env name=VERSION::$(date '+%Y%m%d%H%M')"
        
      - name: Create release
        shell: bash
        run: bash -x /home/deploy/deploy.sh
