name: CI-CD test

on:
  pull_request:
    branches:
      - master
      - main
      - develop

  push:
    branches:
      - master
      - main
      - develop

jobs:
  deploy:
    name: deploy no server remoto
    runs-on: [self-hosted, linux]
    steps:
      - name: Get current date
        run: echo "::set-env name=VERSION::$(date '+%Y%m%d%H%M')"

      - name: Create release
        shell: bash
        run: |
            mkdir -p releases/$VERSION
            cd releases/$VERSION
            pwd
