name: CI-CD test

on:
  pull_request:
    branches:
      - master
      - develop

  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: deploy no server remoto
    runs-on: [self-hosted, linux]
    steps:
      - name: Get current date
        run: echo "::set-env name=VERSION::$(date +%Y%m%d%H%M')"

