name: CI-CD test

on:
  pull_request:
    branches:
      - master
      - develop

  push:
    branches:
      - master
      - develop

  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-env name=VERSION::$(date +%Y%m%d%H%M')"

      - name: Create release
        shell: bash
        run: |
            mkdir -p releases/$VERSION
            cd releases/$VERSION
            
      - name: Download source code
      - uses: actions/checkout@v2
        with:
          ssh-key: ' ${{ secrets.SSH_KEY }}'
                
      - name: Change release
        shell: bash        
        run: |
            cd $GITHUB_WORKSPACE 
            rm ./current
            ln -s releases/$VERSION ./current
            
